"""added new tables for scraper data

Revision ID: 52c3fcbe5d56
Revises: 5d0abea67f16
Create Date: 2025-11-02 20:47:56.113675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '52c3fcbe5d56'
down_revision: Union[str, Sequence[str], None] = '5d0abea67f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('no_of_new_tenders', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_runs_run_at'), 'scrape_runs', ['run_at'], unique=False)
    op.create_table('scraped_tender_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_name', sa.String(), nullable=True),
    sa.Column('number_of_tenders', sa.String(), nullable=True),
    sa.Column('scrape_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_tender_queries_query_name'), 'scraped_tender_queries', ['query_name'], unique=False)
    op.create_table('scraped_tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id_str', sa.String(), nullable=True),
    sa.Column('tender_name', sa.String(), nullable=True),
    sa.Column('tender_url', sa.String(), nullable=True),
    sa.Column('drive_url', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('tdr', sa.String(), nullable=True),
    sa.Column('tendering_authority', sa.String(), nullable=True),
    sa.Column('tender_no', sa.String(), nullable=True),
    sa.Column('tender_id_detail', sa.String(), nullable=True),
    sa.Column('tender_brief', sa.Text(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('document_fees', sa.String(), nullable=True),
    sa.Column('emd', sa.String(), nullable=True),
    sa.Column('tender_value', sa.String(), nullable=True),
    sa.Column('tender_type', sa.String(), nullable=True),
    sa.Column('bidding_type', sa.String(), nullable=True),
    sa.Column('competition_type', sa.String(), nullable=True),
    sa.Column('tender_details', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.String(), nullable=True),
    sa.Column('last_date_of_bid_submission', sa.String(), nullable=True),
    sa.Column('tender_opening_date', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('information_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['scraped_tender_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_tenders_tender_id_str'), 'scraped_tenders', ['tender_id_str'], unique=False)
    op.create_table('scraped_tender_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_description', sa.String(), nullable=True),
    sa.Column('file_size', sa.String(), nullable=True),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['scraped_tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_tender_files')
    op.drop_index(op.f('ix_scraped_tenders_tender_id_str'), table_name='scraped_tenders')
    op.drop_table('scraped_tenders')
    op.drop_index(op.f('ix_scraped_tender_queries_query_name'), table_name='scraped_tender_queries')
    op.drop_table('scraped_tender_queries')
    op.drop_index(op.f('ix_scrape_runs_run_at'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
