"""Add ScrapedEmailLog table for email deduplication

Revision ID: 9d6fa90879e4
Revises: 9dc9d5192910
Create Date: 2025-11-03 13:24:44.248335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '9d6fa90879e4'
down_revision: Union[str, Sequence[str], None] = '9dc9d5192910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_uid', sa.String(), nullable=False),
    sa.Column('email_sender', sa.String(), nullable=False),
    sa.Column('email_received_at', sa.DateTime(), nullable=False),
    sa.Column('tender_url', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scrape_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_received_at', 'scraped_email_logs', ['email_received_at'], unique=False)
    op.create_index('idx_email_uid_tender_url', 'scraped_email_logs', ['email_uid', 'tender_url'], unique=True)
    op.create_index('idx_tender_url', 'scraped_email_logs', ['tender_url'], unique=False)
    op.create_index(op.f('ix_scraped_email_logs_email_received_at'), 'scraped_email_logs', ['email_received_at'], unique=False)
    op.create_index(op.f('ix_scraped_email_logs_email_uid'), 'scraped_email_logs', ['email_uid'], unique=False)
    op.create_index(op.f('ix_scraped_email_logs_tender_url'), 'scraped_email_logs', ['tender_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_email_logs_tender_url'), table_name='scraped_email_logs')
    op.drop_index(op.f('ix_scraped_email_logs_email_uid'), table_name='scraped_email_logs')
    op.drop_index(op.f('ix_scraped_email_logs_email_received_at'), table_name='scraped_email_logs')
    op.drop_index('idx_tender_url', table_name='scraped_email_logs')
    op.drop_index('idx_email_uid_tender_url', table_name='scraped_email_logs')
    op.drop_index('idx_email_received_at', table_name='scraped_email_logs')
    op.drop_table('scraped_email_logs')
    # ### end Alembic commands ###
