"""fixed self-referencing relationship for folders

Revision ID: 9dc9d5192910
Revises: a0a6615a96c2
Create Date: 2025-11-03 02:32:12.001825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '9dc9d5192910'
down_revision: Union[str, Sequence[str], None] = 'a0a6615a96c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_tenders', sa.Column('dms_folder_id', sa.UUID(), nullable=True))
    op.drop_column('scraped_tenders', 'drive_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_tenders', sa.Column('drive_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('scraped_tenders', 'dms_folder_id')
    # ### end Alembic commands ###
