"""updated scraper's schema

Revision ID: dedbec864d0f
Revises: b11b25cdcd86
Create Date: 2025-11-06 16:46:30.105887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'dedbec864d0f'
down_revision: Union[str, Sequence[str], None] = 'b11b25cdcd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_tenders', sa.Column('analysis_status', sa.String(), nullable=False))
    op.add_column('scraped_tenders', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_tenders', 'error_message')
    op.drop_column('scraped_tenders', 'analysis_status')
    # ### end Alembic commands ###
